server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: courseManagement
          uri: http://localhost:8081
          predicates:
            - Path=/courseManagements/** 
        - id: professorApplyment
          uri: http://localhost:8082
          predicates:
            - Path=/professorApplyments/** 
        - id: professorEvaluation
          uri: http://localhost:8083
          predicates:
            - Path=/professorEvaluations/** 
        - id: notification
          uri: http://localhost:8084
          predicates:
            - Path=/smsHistories/** 
        - id: myPage
          uri: http://localhost:8085
          predicates:
            - Path= /applyStatusInquiries/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: courseManagement
          uri: http://courseManagement:8080
          predicates:
            - Path=/courseManagements/** 
        - id: professorApplyment
          uri: http://professorApplyment:8080
          predicates:
            - Path=/professorApplyments/** 
        - id: professorEvaluation
          uri: http://professorEvaluation:8080
          predicates:
            - Path=/professorEvaluations/** 
        - id: notification
          uri: http://notification:8080
          predicates:
            - Path=/smsHistories/** 
        - id: myPage
          uri: http://myPage:8080
          predicates:
            - Path= /applyStatusInquiries/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080