apiVersion: v1
kind: Service
metadata:
  name: professorevaluation
  namespace: professor
  labels:
    app: professorevaluation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: professorevaluation