apiVersion: v1
kind: Service
metadata:
  name: professorEvaluation
  labels:
    app: professorEvaluation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: professorEvaluation