apiVersion: v1
kind: Service
metadata:
  name: coursemanagement
  namespace: professor
  labels:
    app: coursemanagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: coursemanagement