apiVersion: apps/v1
kind: Deployment
metadata:
  name: professorApplyment
  labels:
    app: professorApplyment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: professorApplyment
  template:
    metadata:
      labels:
        app: professorApplyment
    spec:
      containers:
        - name: professorApplyment
          image: username/professorApplyment:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5