apiVersion: v1
kind: Service
metadata:
  name: professorapplyment
  namespace: professor
  labels:
    app: professorapplyment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: professorapplyment